# Sample user data for testing matching functionality

users = [
    {
        "id": "1",
        "name": "Emma Rodriguez",
        "role": "entrepreneur",
        "avatar": "/static/images/placeholder.svg",
        "headline": "Founder of GreenTech Solutions",
        "bio": "Passionate about sustainable technology and creating environmental impact through innovation.",
        "location": "San Francisco, CA",
        "values": ["Sustainability", "Innovation", "Social Impact"],
        "industry": ["CleanTech", "Renewable Energy"],
        "skills": ["Business Development", "Product Management", "Sustainable Design"],
        "experience": 5,
        "interests": ["Renewable Energy", "Climate Tech", "Circular Economy"],
        "goals": ["Scaling business globally", "Reducing carbon footprint", "Securing Series A funding"]
    },
    {
        "id": "2",
        "name": "James Chen",
        "role": "investor",
        "avatar": "/static/images/placeholder.svg",
        "headline": "Angel Investor with focus on Green Initiatives",
        "bio": "I invest in early-stage startups that are committed to environmental sustainability and have scalable business models.",
        "location": "New York, NY",
        "values": ["Sustainability", "Growth", "Innovation"],
        "industry": ["CleanTech", "GreenTech", "AgriTech"],
        "skills": ["Investment Analysis", "Business Strategy", "Networking"],
        "experience": 10,
        "interests": ["Sustainable Startups", "Climate Solutions", "Impact Investing"],
        "goals": ["Supporting climate-focused entrepreneurs", "Building sustainable portfolios", "Creating measurable impact"]
    },
    {
        "id": "3",
        "name": "Sophia Williams",
        "role": "mentor",
        "avatar": "/static/images/placeholder.svg",
        "headline": "Former CTO and Tech Advisor",
        "bio": "Experienced technology leader with a passion for helping startups build scalable and sustainable tech solutions.",
        "location": "Austin, TX",
        "values": ["Knowledge Sharing", "Innovation", "Equality"],
        "industry": ["Software", "AI", "CleanTech"],
        "skills": ["Technical Leadership", "Product Strategy", "Scaling Operations"],
        "experience": 15,
        "interests": ["Emerging Technologies", "Tech for Good", "Diversity in Tech"],
        "goals": ["Mentoring underrepresented founders", "Advising on sustainable tech practices"]
    },
    {
        "id": "4",
        "name": "Michael Johnson",
        "role": "entrepreneur",
        "avatar": "/static/images/placeholder.svg",
        "headline": "Founder of EduTech Innovations",
        "bio": "Building technology solutions that make quality education accessible to all.",
        "location": "Boston, MA",
        "values": ["Education", "Accessibility", "Innovation"],
        "industry": ["EdTech", "SaaS"],
        "skills": ["Product Development", "Education Design", "Business Strategy"],
        "experience": 3,
        "interests": ["Digital Learning", "Educational Equality", "EdTech"],
        "goals": ["Expanding to underserved communities", "Securing seed funding", "Building strategic partnerships"]
    },
    {
        "id": "5",
        "name": "David Kim",
        "role": "investor",
        "avatar": "/static/images/placeholder.svg",
        "headline": "Impact Investor at Future Forward Fund",
        "bio": "Looking for founders with innovative ideas that address significant social or environmental challenges.",
        "location": "Chicago, IL",
        "values": ["Impact", "Innovation", "Diversity"],
        "industry": ["HealthTech", "EdTech", "CleanTech"],
        "skills": ["Financial Analysis", "Impact Assessment", "Venture Capital"],
        "experience": 8,
        "interests": ["Impact Startups", "Sustainable Development", "Social Entrepreneurship"],
        "goals": ["Funding diverse founders", "Creating measurable social impact", "Building sustainable businesses"]
    },
    {
        "id": "6",
        "name": "Olivia Taylor",
        "role": "mentor",
        "avatar": "/static/images/placeholder.svg",
        "headline": "Marketing Executive and Startup Advisor",
        "bio": "Helping purpose-driven startups find their voice and reach their audience.",
        "location": "Los Angeles, CA",
        "values": ["Authenticity", "Creativity", "Purpose"],
        "industry": ["Marketing", "E-commerce", "Social Impact"],
        "skills": ["Brand Strategy", "Digital Marketing", "Growth Hacking"],
        "experience": 12,
        "interests": ["Purpose-Driven Brands", "Sustainable Marketing", "Community Building"],
        "goals": ["Mentoring mission-driven startups", "Promoting sustainable marketing practices", "Building purpose-led brands"]
    }
]